services:

  backend:
    build: ./

    env_file:
      - .env
    ports:
      - "8080:8080"

    networks:
      - app-network


  db:
    image: postgres
    restart: always
    shm_size: 256mb

    environment:
      POSTGRES_DB: Consultas_API
      POSTGRES_PASSWORD: 1234

    ports:
      - "5432:5432"
    networks:
      - app-network


  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
