services:

  backend:
    build: .

    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db

    networks:
      - app-network


  db:
    image: postgres
    restart: always
    shm_size: 256mb

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"
    networks:
      - app-network


  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge